/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AgendarRouteImport } from './routes/agendar'
import { Route as ProfessionalRouteImport } from './routes/_professional'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfessionalMinhasComissoesRouteImport } from './routes/_professional.minhas-comissoes'
import { Route as ProfessionalMinhaAgendaRouteImport } from './routes/_professional.minha-agenda'
import { Route as AdminServicosRouteImport } from './routes/_admin.servicos'
import { Route as AdminRelatoriosRouteImport } from './routes/_admin.relatorios'
import { Route as AdminPromocoesRouteImport } from './routes/_admin.promocoes'
import { Route as AdminProfissionaisRouteImport } from './routes/_admin.profissionais'
import { Route as AdminProdutosRouteImport } from './routes/_admin.produtos'
import { Route as AdminMaisRouteImport } from './routes/_admin.mais'
import { Route as AdminFinanceiroRouteImport } from './routes/_admin.financeiro'
import { Route as AdminFidelidadeRouteImport } from './routes/_admin.fidelidade'
import { Route as AdminClientesRouteImport } from './routes/_admin.clientes'
import { Route as AdminAgendaRouteImport } from './routes/_admin.agenda'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarRoute = AgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalRoute = ProfessionalRouteImport.update({
  id: '/_professional',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalMinhasComissoesRoute =
  ProfessionalMinhasComissoesRouteImport.update({
    id: '/minhas-comissoes',
    path: '/minhas-comissoes',
    getParentRoute: () => ProfessionalRoute,
  } as any)
const ProfessionalMinhaAgendaRoute = ProfessionalMinhaAgendaRouteImport.update({
  id: '/minha-agenda',
  path: '/minha-agenda',
  getParentRoute: () => ProfessionalRoute,
} as any)
const AdminServicosRoute = AdminServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromocoesRoute = AdminPromocoesRouteImport.update({
  id: '/promocoes',
  path: '/promocoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfissionaisRoute = AdminProfissionaisRouteImport.update({
  id: '/profissionais',
  path: '/profissionais',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMaisRoute = AdminMaisRouteImport.update({
  id: '/mais',
  path: '/mais',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFidelidadeRoute = AdminFidelidadeRouteImport.update({
  id: '/fidelidade',
  path: '/fidelidade',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgendaRoute = AdminAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/agenda': typeof AdminAgendaRoute
  '/clientes': typeof AdminClientesRoute
  '/fidelidade': typeof AdminFidelidadeRoute
  '/financeiro': typeof AdminFinanceiroRoute
  '/mais': typeof AdminMaisRoute
  '/produtos': typeof AdminProdutosRoute
  '/profissionais': typeof AdminProfissionaisRoute
  '/promocoes': typeof AdminPromocoesRoute
  '/relatorios': typeof AdminRelatoriosRoute
  '/servicos': typeof AdminServicosRoute
  '/minha-agenda': typeof ProfessionalMinhaAgendaRoute
  '/minhas-comissoes': typeof ProfessionalMinhasComissoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/agenda': typeof AdminAgendaRoute
  '/clientes': typeof AdminClientesRoute
  '/fidelidade': typeof AdminFidelidadeRoute
  '/financeiro': typeof AdminFinanceiroRoute
  '/mais': typeof AdminMaisRoute
  '/produtos': typeof AdminProdutosRoute
  '/profissionais': typeof AdminProfissionaisRoute
  '/promocoes': typeof AdminPromocoesRoute
  '/relatorios': typeof AdminRelatoriosRoute
  '/servicos': typeof AdminServicosRoute
  '/minha-agenda': typeof ProfessionalMinhaAgendaRoute
  '/minhas-comissoes': typeof ProfessionalMinhasComissoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_professional': typeof ProfessionalRouteWithChildren
  '/agendar': typeof AgendarRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/_admin/agenda': typeof AdminAgendaRoute
  '/_admin/clientes': typeof AdminClientesRoute
  '/_admin/fidelidade': typeof AdminFidelidadeRoute
  '/_admin/financeiro': typeof AdminFinanceiroRoute
  '/_admin/mais': typeof AdminMaisRoute
  '/_admin/produtos': typeof AdminProdutosRoute
  '/_admin/profissionais': typeof AdminProfissionaisRoute
  '/_admin/promocoes': typeof AdminPromocoesRoute
  '/_admin/relatorios': typeof AdminRelatoriosRoute
  '/_admin/servicos': typeof AdminServicosRoute
  '/_professional/minha-agenda': typeof ProfessionalMinhaAgendaRoute
  '/_professional/minhas-comissoes': typeof ProfessionalMinhasComissoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agendar'
    | '/app'
    | '/login'
    | '/logout'
    | '/agenda'
    | '/clientes'
    | '/fidelidade'
    | '/financeiro'
    | '/mais'
    | '/produtos'
    | '/profissionais'
    | '/promocoes'
    | '/relatorios'
    | '/servicos'
    | '/minha-agenda'
    | '/minhas-comissoes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendar'
    | '/app'
    | '/login'
    | '/logout'
    | '/agenda'
    | '/clientes'
    | '/fidelidade'
    | '/financeiro'
    | '/mais'
    | '/produtos'
    | '/profissionais'
    | '/promocoes'
    | '/relatorios'
    | '/servicos'
    | '/minha-agenda'
    | '/minhas-comissoes'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_professional'
    | '/agendar'
    | '/app'
    | '/login'
    | '/logout'
    | '/_admin/agenda'
    | '/_admin/clientes'
    | '/_admin/fidelidade'
    | '/_admin/financeiro'
    | '/_admin/mais'
    | '/_admin/produtos'
    | '/_admin/profissionais'
    | '/_admin/promocoes'
    | '/_admin/relatorios'
    | '/_admin/servicos'
    | '/_professional/minha-agenda'
    | '/_professional/minhas-comissoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ProfessionalRoute: typeof ProfessionalRouteWithChildren
  AgendarRoute: typeof AgendarRoute
  AppRoute: typeof AppRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar': {
      id: '/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AgendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_professional': {
      id: '/_professional'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProfessionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_professional/minhas-comissoes': {
      id: '/_professional/minhas-comissoes'
      path: '/minhas-comissoes'
      fullPath: '/minhas-comissoes'
      preLoaderRoute: typeof ProfessionalMinhasComissoesRouteImport
      parentRoute: typeof ProfessionalRoute
    }
    '/_professional/minha-agenda': {
      id: '/_professional/minha-agenda'
      path: '/minha-agenda'
      fullPath: '/minha-agenda'
      preLoaderRoute: typeof ProfessionalMinhaAgendaRouteImport
      parentRoute: typeof ProfessionalRoute
    }
    '/_admin/servicos': {
      id: '/_admin/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof AdminServicosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/relatorios': {
      id: '/_admin/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/promocoes': {
      id: '/_admin/promocoes'
      path: '/promocoes'
      fullPath: '/promocoes'
      preLoaderRoute: typeof AdminPromocoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/profissionais': {
      id: '/_admin/profissionais'
      path: '/profissionais'
      fullPath: '/profissionais'
      preLoaderRoute: typeof AdminProfissionaisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/produtos': {
      id: '/_admin/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/mais': {
      id: '/_admin/mais'
      path: '/mais'
      fullPath: '/mais'
      preLoaderRoute: typeof AdminMaisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/financeiro': {
      id: '/_admin/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/fidelidade': {
      id: '/_admin/fidelidade'
      path: '/fidelidade'
      fullPath: '/fidelidade'
      preLoaderRoute: typeof AdminFidelidadeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/clientes': {
      id: '/_admin/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/agenda': {
      id: '/_admin/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AdminAgendaRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAgendaRoute: typeof AdminAgendaRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminFidelidadeRoute: typeof AdminFidelidadeRoute
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminMaisRoute: typeof AdminMaisRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
  AdminProfissionaisRoute: typeof AdminProfissionaisRoute
  AdminPromocoesRoute: typeof AdminPromocoesRoute
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminServicosRoute: typeof AdminServicosRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgendaRoute: AdminAgendaRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminFidelidadeRoute: AdminFidelidadeRoute,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminMaisRoute: AdminMaisRoute,
  AdminProdutosRoute: AdminProdutosRoute,
  AdminProfissionaisRoute: AdminProfissionaisRoute,
  AdminPromocoesRoute: AdminPromocoesRoute,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminServicosRoute: AdminServicosRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProfessionalRouteChildren {
  ProfessionalMinhaAgendaRoute: typeof ProfessionalMinhaAgendaRoute
  ProfessionalMinhasComissoesRoute: typeof ProfessionalMinhasComissoesRoute
}

const ProfessionalRouteChildren: ProfessionalRouteChildren = {
  ProfessionalMinhaAgendaRoute: ProfessionalMinhaAgendaRoute,
  ProfessionalMinhasComissoesRoute: ProfessionalMinhasComissoesRoute,
}

const ProfessionalRouteWithChildren = ProfessionalRoute._addFileChildren(
  ProfessionalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ProfessionalRoute: ProfessionalRouteWithChildren,
  AgendarRoute: AgendarRoute,
  AppRoute: AppRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
