/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AgendarRouteImport } from './routes/agendar'
import { Route as StaffRouteImport } from './routes/_staff'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StaffServicosRouteImport } from './routes/_staff.servicos'
import { Route as StaffRelatoriosRouteImport } from './routes/_staff.relatorios'
import { Route as StaffPromocoesRouteImport } from './routes/_staff.promocoes'
import { Route as StaffProfissionaisRouteImport } from './routes/_staff.profissionais'
import { Route as StaffProdutosRouteImport } from './routes/_staff.produtos'
import { Route as StaffMinhasComissoesRouteImport } from './routes/_staff.minhas-comissoes'
import { Route as StaffMinhaAgendaRouteImport } from './routes/_staff.minha-agenda'
import { Route as StaffMaisRouteImport } from './routes/_staff.mais'
import { Route as StaffLembretesRouteImport } from './routes/_staff.lembretes'
import { Route as StaffFinanceiroRouteImport } from './routes/_staff.financeiro'
import { Route as StaffFidelidadeRouteImport } from './routes/_staff.fidelidade'
import { Route as StaffConfiguracoesRouteImport } from './routes/_staff.configuracoes'
import { Route as StaffClientesRouteImport } from './routes/_staff.clientes'
import { Route as StaffAgendaRouteImport } from './routes/_staff.agenda'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarRoute = AgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/_staff',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffServicosRoute = StaffServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => StaffRoute,
} as any)
const StaffRelatoriosRoute = StaffRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => StaffRoute,
} as any)
const StaffPromocoesRoute = StaffPromocoesRouteImport.update({
  id: '/promocoes',
  path: '/promocoes',
  getParentRoute: () => StaffRoute,
} as any)
const StaffProfissionaisRoute = StaffProfissionaisRouteImport.update({
  id: '/profissionais',
  path: '/profissionais',
  getParentRoute: () => StaffRoute,
} as any)
const StaffProdutosRoute = StaffProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => StaffRoute,
} as any)
const StaffMinhasComissoesRoute = StaffMinhasComissoesRouteImport.update({
  id: '/minhas-comissoes',
  path: '/minhas-comissoes',
  getParentRoute: () => StaffRoute,
} as any)
const StaffMinhaAgendaRoute = StaffMinhaAgendaRouteImport.update({
  id: '/minha-agenda',
  path: '/minha-agenda',
  getParentRoute: () => StaffRoute,
} as any)
const StaffMaisRoute = StaffMaisRouteImport.update({
  id: '/mais',
  path: '/mais',
  getParentRoute: () => StaffRoute,
} as any)
const StaffLembretesRoute = StaffLembretesRouteImport.update({
  id: '/lembretes',
  path: '/lembretes',
  getParentRoute: () => StaffRoute,
} as any)
const StaffFinanceiroRoute = StaffFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => StaffRoute,
} as any)
const StaffFidelidadeRoute = StaffFidelidadeRouteImport.update({
  id: '/fidelidade',
  path: '/fidelidade',
  getParentRoute: () => StaffRoute,
} as any)
const StaffConfiguracoesRoute = StaffConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => StaffRoute,
} as any)
const StaffClientesRoute = StaffClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => StaffRoute,
} as any)
const StaffAgendaRoute = StaffAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => StaffRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/agenda': typeof StaffAgendaRoute
  '/clientes': typeof StaffClientesRoute
  '/configuracoes': typeof StaffConfiguracoesRoute
  '/fidelidade': typeof StaffFidelidadeRoute
  '/financeiro': typeof StaffFinanceiroRoute
  '/lembretes': typeof StaffLembretesRoute
  '/mais': typeof StaffMaisRoute
  '/minha-agenda': typeof StaffMinhaAgendaRoute
  '/minhas-comissoes': typeof StaffMinhasComissoesRoute
  '/produtos': typeof StaffProdutosRoute
  '/profissionais': typeof StaffProfissionaisRoute
  '/promocoes': typeof StaffPromocoesRoute
  '/relatorios': typeof StaffRelatoriosRoute
  '/servicos': typeof StaffServicosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agendar': typeof AgendarRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/agenda': typeof StaffAgendaRoute
  '/clientes': typeof StaffClientesRoute
  '/configuracoes': typeof StaffConfiguracoesRoute
  '/fidelidade': typeof StaffFidelidadeRoute
  '/financeiro': typeof StaffFinanceiroRoute
  '/lembretes': typeof StaffLembretesRoute
  '/mais': typeof StaffMaisRoute
  '/minha-agenda': typeof StaffMinhaAgendaRoute
  '/minhas-comissoes': typeof StaffMinhasComissoesRoute
  '/produtos': typeof StaffProdutosRoute
  '/profissionais': typeof StaffProfissionaisRoute
  '/promocoes': typeof StaffPromocoesRoute
  '/relatorios': typeof StaffRelatoriosRoute
  '/servicos': typeof StaffServicosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_staff': typeof StaffRouteWithChildren
  '/agendar': typeof AgendarRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/_staff/agenda': typeof StaffAgendaRoute
  '/_staff/clientes': typeof StaffClientesRoute
  '/_staff/configuracoes': typeof StaffConfiguracoesRoute
  '/_staff/fidelidade': typeof StaffFidelidadeRoute
  '/_staff/financeiro': typeof StaffFinanceiroRoute
  '/_staff/lembretes': typeof StaffLembretesRoute
  '/_staff/mais': typeof StaffMaisRoute
  '/_staff/minha-agenda': typeof StaffMinhaAgendaRoute
  '/_staff/minhas-comissoes': typeof StaffMinhasComissoesRoute
  '/_staff/produtos': typeof StaffProdutosRoute
  '/_staff/profissionais': typeof StaffProfissionaisRoute
  '/_staff/promocoes': typeof StaffPromocoesRoute
  '/_staff/relatorios': typeof StaffRelatoriosRoute
  '/_staff/servicos': typeof StaffServicosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agendar'
    | '/app'
    | '/login'
    | '/logout'
    | '/agenda'
    | '/clientes'
    | '/configuracoes'
    | '/fidelidade'
    | '/financeiro'
    | '/lembretes'
    | '/mais'
    | '/minha-agenda'
    | '/minhas-comissoes'
    | '/produtos'
    | '/profissionais'
    | '/promocoes'
    | '/relatorios'
    | '/servicos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agendar'
    | '/app'
    | '/login'
    | '/logout'
    | '/agenda'
    | '/clientes'
    | '/configuracoes'
    | '/fidelidade'
    | '/financeiro'
    | '/lembretes'
    | '/mais'
    | '/minha-agenda'
    | '/minhas-comissoes'
    | '/produtos'
    | '/profissionais'
    | '/promocoes'
    | '/relatorios'
    | '/servicos'
  id:
    | '__root__'
    | '/'
    | '/_staff'
    | '/agendar'
    | '/app'
    | '/login'
    | '/logout'
    | '/_staff/agenda'
    | '/_staff/clientes'
    | '/_staff/configuracoes'
    | '/_staff/fidelidade'
    | '/_staff/financeiro'
    | '/_staff/lembretes'
    | '/_staff/mais'
    | '/_staff/minha-agenda'
    | '/_staff/minhas-comissoes'
    | '/_staff/produtos'
    | '/_staff/profissionais'
    | '/_staff/promocoes'
    | '/_staff/relatorios'
    | '/_staff/servicos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StaffRoute: typeof StaffRouteWithChildren
  AgendarRoute: typeof AgendarRoute
  AppRoute: typeof AppRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar': {
      id: '/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AgendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_staff': {
      id: '/_staff'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_staff/servicos': {
      id: '/_staff/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof StaffServicosRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/relatorios': {
      id: '/_staff/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof StaffRelatoriosRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/promocoes': {
      id: '/_staff/promocoes'
      path: '/promocoes'
      fullPath: '/promocoes'
      preLoaderRoute: typeof StaffPromocoesRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/profissionais': {
      id: '/_staff/profissionais'
      path: '/profissionais'
      fullPath: '/profissionais'
      preLoaderRoute: typeof StaffProfissionaisRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/produtos': {
      id: '/_staff/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof StaffProdutosRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/minhas-comissoes': {
      id: '/_staff/minhas-comissoes'
      path: '/minhas-comissoes'
      fullPath: '/minhas-comissoes'
      preLoaderRoute: typeof StaffMinhasComissoesRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/minha-agenda': {
      id: '/_staff/minha-agenda'
      path: '/minha-agenda'
      fullPath: '/minha-agenda'
      preLoaderRoute: typeof StaffMinhaAgendaRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/mais': {
      id: '/_staff/mais'
      path: '/mais'
      fullPath: '/mais'
      preLoaderRoute: typeof StaffMaisRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/lembretes': {
      id: '/_staff/lembretes'
      path: '/lembretes'
      fullPath: '/lembretes'
      preLoaderRoute: typeof StaffLembretesRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/financeiro': {
      id: '/_staff/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof StaffFinanceiroRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/fidelidade': {
      id: '/_staff/fidelidade'
      path: '/fidelidade'
      fullPath: '/fidelidade'
      preLoaderRoute: typeof StaffFidelidadeRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/configuracoes': {
      id: '/_staff/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof StaffConfiguracoesRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/clientes': {
      id: '/_staff/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof StaffClientesRouteImport
      parentRoute: typeof StaffRoute
    }
    '/_staff/agenda': {
      id: '/_staff/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof StaffAgendaRouteImport
      parentRoute: typeof StaffRoute
    }
  }
}

interface StaffRouteChildren {
  StaffAgendaRoute: typeof StaffAgendaRoute
  StaffClientesRoute: typeof StaffClientesRoute
  StaffConfiguracoesRoute: typeof StaffConfiguracoesRoute
  StaffFidelidadeRoute: typeof StaffFidelidadeRoute
  StaffFinanceiroRoute: typeof StaffFinanceiroRoute
  StaffLembretesRoute: typeof StaffLembretesRoute
  StaffMaisRoute: typeof StaffMaisRoute
  StaffMinhaAgendaRoute: typeof StaffMinhaAgendaRoute
  StaffMinhasComissoesRoute: typeof StaffMinhasComissoesRoute
  StaffProdutosRoute: typeof StaffProdutosRoute
  StaffProfissionaisRoute: typeof StaffProfissionaisRoute
  StaffPromocoesRoute: typeof StaffPromocoesRoute
  StaffRelatoriosRoute: typeof StaffRelatoriosRoute
  StaffServicosRoute: typeof StaffServicosRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffAgendaRoute: StaffAgendaRoute,
  StaffClientesRoute: StaffClientesRoute,
  StaffConfiguracoesRoute: StaffConfiguracoesRoute,
  StaffFidelidadeRoute: StaffFidelidadeRoute,
  StaffFinanceiroRoute: StaffFinanceiroRoute,
  StaffLembretesRoute: StaffLembretesRoute,
  StaffMaisRoute: StaffMaisRoute,
  StaffMinhaAgendaRoute: StaffMinhaAgendaRoute,
  StaffMinhasComissoesRoute: StaffMinhasComissoesRoute,
  StaffProdutosRoute: StaffProdutosRoute,
  StaffProfissionaisRoute: StaffProfissionaisRoute,
  StaffPromocoesRoute: StaffPromocoesRoute,
  StaffRelatoriosRoute: StaffRelatoriosRoute,
  StaffServicosRoute: StaffServicosRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StaffRoute: StaffRouteWithChildren,
  AgendarRoute: AgendarRoute,
  AppRoute: AppRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
