defmodule LabelleBack.Repo.Migrations.AddAppointmentServicesAndClientReminders do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:client_reminders, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :kind, :text, null: false
      add :status, :text, default: "pendente"
      add :channel, :text, default: "whatsapp"
      add :due_date, :date, null: false
      add :message, :text, null: false
      add :client_name, :text
      add :client_phone, :text
      add :sent_at, :utc_datetime_usec
      add :sent_via, :text
      add :failure_reason, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :client_id,
          references(:clients,
            column: :id,
            name: "client_reminders_client_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:appointment_services, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :service_name, :text
      add :price, :decimal
      add :duration_minutes, :bigint
      add :unplanned, :boolean, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :appointment_id,
          references(:appointments,
            column: :id,
            name: "appointment_services_appointment_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :service_id,
          references(:services,
            column: :id,
            name: "appointment_services_service_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:appointment_services, "appointment_services_appointment_id_fkey")

    drop constraint(:appointment_services, "appointment_services_service_id_fkey")

    drop table(:appointment_services)

    drop constraint(:client_reminders, "client_reminders_client_id_fkey")

    drop table(:client_reminders)
  end
end
