defmodule LabelleBack.Repo.Migrations.AddDomainCheckConstraints do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create constraint(:appointment_services, :appointment_services_price_non_negative,
             check: """
               price >= 0
             """
           )

    create constraint(:appointment_services, :appointment_services_duration_positive,
             check: """
               duration_minutes > 0
             """
           )

    create constraint(:appointments, :appointments_status_valid,
             check: """
               status IN ('agendado', 'confirmado', 'em_atendimento', 'concluido', 'cancelado')
             """
           )

    create constraint(:appointments, :appointments_price_non_negative,
             check: """
               price >= 0
             """
           )

    create constraint(:appointments, :appointments_duration_positive,
             check: """
               duration_minutes > 0
             """
           )

    create constraint(:services, :services_price_non_negative,
             check: """
               price >= 0
             """
           )

    create constraint(:services, :services_duration_positive,
             check: """
               duration_minutes > 0
             """
           )

    create constraint(:transactions, :transactions_status_valid,
             check: """
               status IN ('pendente_confirmacao', 'pagamento_parcial', 'pago', 'cancelado', 'estornado')
             """
           )

    create constraint(:transactions, :transactions_amount_non_negative,
             check: """
               amount >= 0
             """
           )
  end

  def down do
    drop_if_exists constraint(:transactions, :transactions_amount_non_negative)

    drop_if_exists constraint(:transactions, :transactions_status_valid)

    drop_if_exists constraint(:services, :services_duration_positive)

    drop_if_exists constraint(:services, :services_price_non_negative)

    drop_if_exists constraint(:appointments, :appointments_duration_positive)

    drop_if_exists constraint(:appointments, :appointments_price_non_negative)

    drop_if_exists constraint(:appointments, :appointments_status_valid)

    drop_if_exists constraint(:appointment_services, :appointment_services_duration_positive)

    drop_if_exists constraint(:appointment_services, :appointment_services_price_non_negative)
  end
end
