defmodule LabelleBack.Repo.Migrations.AddStudioSettings do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:studio_settings, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :singleton, :boolean, null: false, default: true
      add :name, :text, null: false, default: "La Belle Studio"
      add :whatsapp_phone, :text, null: false
      add :zip_code, :text
      add :street, :text
      add :neighborhood, :text
      add :city, :text
      add :state, :text
      add :message_confirmation, :text, null: false
      add :message_reminder, :text, null: false
      add :message_thank_you, :text, null: false
      add :message_reengagement, :text, null: false
      add :message_new_booking_notification, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:studio_settings, [:singleton], name: "studio_settings_singleton_index")
  end

  def down do
    drop_if_exists unique_index(:studio_settings, [:singleton],
                     name: "studio_settings_singleton_index"
                   )

    drop table(:studio_settings)
  end
end
