defmodule LabelleBack.Repo.Migrations.AddStudioDomain do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      add :role, :text, null: false, default: "user"
    end

    create table(:transactions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :type, :text, null: false
      add :category, :text
      add :description, :text
      add :amount, :decimal, null: false
      add :net_amount, :decimal
      add :total_fees, :decimal, default: "0"
      add :date, :date, null: false
      add :payment_method, :text, default: "a_definir"
      add :status, :text, default: "pago"
      add :appointment_id, :uuid
      add :professional_id, :uuid
      add :client_id, :uuid
    end

    create table(:services, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :category, :text, null: false
      add :price, :decimal, null: false
      add :duration_minutes, :bigint, null: false
      add :commission_percent, :decimal
      add :recurrence_days, :bigint
      add :description, :text
      add :is_active, :boolean, default: true
    end

    create table(:promotions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :discount_type, :text, null: false
      add :discount_value, :decimal, null: false
      add :start_date, :date
      add :end_date, :date
      add :is_active, :boolean, default: true
      add :rules, :text

      add :service_id,
          references(:services,
            column: :id,
            name: "promotions_service_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:professionals, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :phone, :text, null: false
      add :email, :text
      add :type, :text, default: "comissao"
      add :commission_percent, :decimal, default: "40"
      add :rent_value, :decimal
      add :avatar_url, :text
      add :color, :text
      add :is_active, :boolean, default: true
      add :work_days, {:array, :bigint}
      add :work_start, :time
      add :work_end, :time

      add :user_id,
          references(:users,
            column: :id,
            name: "professionals_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    create table(:professional_services, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :professional_id,
          references(:professionals,
            column: :id,
            name: "professional_services_professional_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :service_id,
          references(:services,
            column: :id,
            name: "professional_services_service_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:professional_services, [:professional_id, :service_id],
             name: "professional_services_unique_professional_service_index"
           )

    create table(:products, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :category, :text
      add :price, :decimal, null: false
      add :cost, :decimal
      add :quantity, :bigint, default: 0
      add :min_quantity, :bigint, default: 5
      add :description, :text
      add :is_active, :boolean, default: true
    end

    create table(:payments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :payment_date, :date, null: false
      add :payment_method, :text, null: false
      add :amount, :decimal, null: false
      add :fee_percent, :decimal, default: "0"
      add :fee_amount, :decimal, default: "0"
      add :net_amount, :decimal
      add :installments, :bigint, default: 1
      add :card_brand, :text
      add :status, :text, default: "confirmado"
      add :origin, :text, default: "manual"
      add :gateway_name, :text
      add :gateway_transaction_id, :text
      add :gateway_status, :text
      add :gateway_payment_method, :text
      add :gateway_payload, :map
      add :gateway_confirmed_at, :utc_datetime_usec
      add :receipt_url, :text
      add :reconciled, :boolean, default: false
      add :reconciled_at, :utc_datetime_usec
      add :reconciliation_notes, :text

      add :transaction_id,
          references(:transactions,
            column: :id,
            name: "payments_transaction_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :appointment_id, :uuid
      add :client_id, :uuid
      add :professional_id, :uuid
    end

    create table(:clients, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :phone, :text, null: false
      add :phone_normalized, :text
      add :email, :text
      add :birthday, :date
      add :notes, :text
      add :preferences, :text
      add :loyalty_points, :bigint, default: 0
      add :loyalty_tier, :text, default: "bronze"
      add :total_spent, :decimal, default: "0"
      add :visit_count, :bigint, default: 0
      add :avatar_url, :text
      add :is_active, :boolean, default: true
      add :source, :text, default: "gestao"
      add :first_appointment_date, :date
      add :last_appointment_date, :date
    end

    create unique_index(:clients, [:phone_normalized],
             name: "clients_unique_phone_normalized_index"
           )

    create table(:appointments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:transactions) do
      modify :appointment_id,
             references(:appointments,
               column: :id,
               name: "transactions_appointment_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :professional_id,
             references(:professionals,
               column: :id,
               name: "transactions_professional_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :client_id,
             references(:clients,
               column: :id,
               name: "transactions_client_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:payments) do
      modify :appointment_id,
             references(:appointments,
               column: :id,
               name: "payments_appointment_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :client_id,
             references(:clients,
               column: :id,
               name: "payments_client_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :professional_id,
             references(:professionals,
               column: :id,
               name: "payments_professional_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:appointments) do
      add :client_name, :text, null: false
      add :client_phone, :text
      add :professional_name, :text
      add :service_name, :text
      add :date, :date, null: false
      add :time, :time, null: false
      add :duration_minutes, :bigint
      add :price, :decimal
      add :status, :text, default: "agendado"
      add :payment_method, :text
      add :notes, :text
      add :source, :text, default: "manual"

      add :client_id,
          references(:clients,
            column: :id,
            name: "appointments_client_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :professional_id,
          references(:professionals,
            column: :id,
            name: "appointments_professional_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :service_id,
          references(:services,
            column: :id,
            name: "appointments_service_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:appointments, "appointments_client_id_fkey")

    drop constraint(:appointments, "appointments_professional_id_fkey")

    drop constraint(:appointments, "appointments_service_id_fkey")

    alter table(:appointments) do
      remove :service_id
      remove :professional_id
      remove :client_id
      remove :source
      remove :notes
      remove :payment_method
      remove :status
      remove :price
      remove :duration_minutes
      remove :time
      remove :date
      remove :service_name
      remove :professional_name
      remove :client_phone
      remove :client_name
    end

    drop constraint(:payments, "payments_appointment_id_fkey")

    drop constraint(:payments, "payments_client_id_fkey")

    drop constraint(:payments, "payments_professional_id_fkey")

    alter table(:payments) do
      modify :professional_id, :uuid
      modify :client_id, :uuid
      modify :appointment_id, :uuid
    end

    drop constraint(:transactions, "transactions_appointment_id_fkey")

    drop constraint(:transactions, "transactions_professional_id_fkey")

    drop constraint(:transactions, "transactions_client_id_fkey")

    alter table(:transactions) do
      modify :client_id, :uuid
      modify :professional_id, :uuid
      modify :appointment_id, :uuid
    end

    drop table(:appointments)

    drop_if_exists unique_index(:clients, [:phone_normalized],
                     name: "clients_unique_phone_normalized_index"
                   )

    drop table(:clients)

    drop constraint(:payments, "payments_transaction_id_fkey")

    drop table(:payments)

    drop table(:products)

    drop constraint(:professional_services, "professional_services_professional_id_fkey")

    drop constraint(:professional_services, "professional_services_service_id_fkey")

    drop_if_exists unique_index(:professional_services, [:professional_id, :service_id],
                     name: "professional_services_unique_professional_service_index"
                   )

    drop table(:professional_services)

    drop constraint(:professionals, "professionals_user_id_fkey")

    drop table(:professionals)

    drop constraint(:promotions, "promotions_service_id_fkey")

    drop table(:promotions)

    drop table(:services)

    drop table(:transactions)

    alter table(:users) do
      remove :role
    end
  end
end
