defmodule LabelleBack.Repo.Migrations.AppointmentStatusNotNull do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:appointments) do
      modify :status, :text, null: false
    end
  end

  def down do
    alter table(:appointments) do
      modify :status, :text, null: true
    end
  end
end
