services:
  db:
    image: postgres:16-alpine
    container_name: labelle_back_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: labelle_back_dev
    ports:
      - "5433:5432"
    volumes:
      - labelle_back_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  labelle_back_pg_data:
